### PR TITLE
unpin requirements

### PR DESCRIPTION
**Pull request by rgbkrk**
I'd like to propose not strictly pinning dependencies in this package, allowing users of this library to have their own pinned versions instead. If accepted and released, fantastic! If rejected, I'll make a fork (for now) that allows us to relax the dependencies.

### CODE REVIEW

**Comment by ggreg** [comment]
Maybe we could use an environment variable to make it flexible.

**Comment by ggreg** [comment]
Is the problem conflicting versions when using `presto-python-client` in a project with overlapping dependencies?

**Comment by rgbkrk** [comment]
That is correct. In fact, I want to use this in notebook environments where a large software stack is installed.

**Comment by thibeco** [comment]
Any update on this?
`requests` and `six` packages are currently clashing with other libraries causing dependencies resolution errors when using `pipenv` for example.

**Comment by ggreg** [comment]
Accepting this pull-request to unblock integration with other libraries

**Comment by ggreg** [comment]
Thanks for the pull request and raising this issue!

**Pull request merged**
